# Linear Programming: The Simplex Method

In [4]:
import sys

sys.path.append('..')

### 1. Primal Problem

##### Example #1.1

$$
\min -4x_1 - 2x_2, \quad \text{subject to} \quad
\left\{
\begin{array}{l}
x_1 + x_2 + x_3 = 5 \\
2x_1 + 0.5x_2 + x_4 = 8 \\
x \geq 0
\end{array}
\right.
$$

<br/>

$$
    A = \begin{pmatrix}        
        1 & 1   & 1 & 0 \\
        2 & 0.5 & 0 & 1 \\
    \end{pmatrix},

    b = \begin{pmatrix} 
        5 \\
        8 \\
    \end{pmatrix}
$$

In [5]:
import numpy as np
from modules.optimize.constrained.linear_programming.simplex_method import primal

c = np.array([-4., -2., 0., 0.])

A = np.array([
    [1.,  1., 1., 0.],
    [2., 0.5, 0., 1.]
])

b = np.array([5., 8.])

primal(c, A, b, [2, 3], 100)

(array([3.66666667, 1.33333333, 0.        , 0.        ]),
 np.float64(-17.333333333333332),
 array([0.75, 0.25, 0.  , 0.  ]),
 3,
 False)

##### Example #1.2

$$
\min 3x_1 + x_2 + x_3, \quad \text{subject to} \quad
\left\{
\begin{array}{l}
2x_1 + x_2 + x_3 \leq 2 \\
x_1 - x_2 - x_3 \leq -1 \\
x \geq 0
\end{array}
\right.
$$

<br/>

<center>
    <h3>Standard form</h3>
</center>

$$
\min 3x_1 + x_2 + x_3, \quad \text{subject to} \quad
\left\{
\begin{array}{l}
2x_1 + x_2 + x_3 + x_4 = 2 \\
x_1 - x_2 - x_3 + x_5 = -1 \\
x \geq 0
\end{array}
\right.
$$

<br/>

$$
    A = \begin{pmatrix}        
        2 & 1  & 1  & 1 & 0 \\
        1 & -1 & -1 & 0 & 1 \\
    \end{pmatrix},

    b = \begin{pmatrix} 
        2 \\
        -1 \\
    \end{pmatrix}
$$

<center>
    <h3>Phase I</h3>
</center>

$$
\min z_1, \quad \text{subject to} \quad
\left\{
\begin{array}{l}
2x_1 + x_2 + x_3 + x_4 = 2 \\
x_1 - x_2 - x_3 + x_5 - z_1 = -1 \\
x \geq 0, z \geq 0
\end{array}
\right.
$$

<br/>

$$
    A = \begin{pmatrix}        
        2 & 1  & 1  & 1 & 0 & 0  \\
        1 & -1 & -1 & 0 & 1 & -1 \\
    \end{pmatrix},

    b = \begin{pmatrix} 
        2 \\
        -1 \\
    \end{pmatrix}
$$

In [6]:
c = np.array([0., 0., 0., 0., 0., 1.])

A = np.array([
    [2.,  1.,  1., 1., 0.,  0.],
    [1., -1., -1., 0., 1., -1.]
])

b = np.array([2., -1.])

primal(c, A, b, [3, 5], 100)

(array([0., 1., 0., 1., 0., 0.]),
 np.float64(0.0),
 array([0., 1., 0., 1., 0., 0.]),
 2,
 False)

<center>
    <h3>
        Phase II
    </h3>
</center>

$$
\min 3x_1 + x_2 + x_3, \quad \text{subject to} \quad
\left\{
\begin{array}{l}
2x_1 + x_2 + x_3 + x_4 = 2 \\
x_1 - x_2 - x_3 + x_5 = -1 \\
x \geq 0
\end{array}
\right.
$$

<br/>

$$
    A = \begin{pmatrix}        
        2 & 1  & 1  & 1 & 0 \\
        1 & -1 & -1 & 0 & 1 \\
    \end{pmatrix},

    b = \begin{pmatrix} 
        2 \\
        -1 \\
    \end{pmatrix},

    \{1, 3\}
$$

In [7]:
c = np.array([3., 1., 1., 0., 0.])

A = np.array([
    [2.,  1.,  1., 1., 0.],
    [1., -1., -1., 0., 1.]
])

b = np.array([2., -1.])

primal(c, A, b, [1, 3], 100)

(array([0., 1., 0., 1., 0.]),
 np.float64(1.0),
 array([0., 0., 0., 0., 0.]),
 1,
 False)